# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  eyes_tilt_joint:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.2
    min_position: -1.2
  neck_pan_joint:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  neck_tilt_joint:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  vergence_joint:
    has_velocity_limits: false
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  version_joint:
    has_velocity_limits: false
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
