vizzy:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Torso Position Controllers
  waist_position_controller:
    type: effort_controllers/JointPositionController
    joint: waist_joint
    pid: {p: 300.0, i: 10.0, d: 0.0}

  # Head Position Controllers
  neck_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_pan_joint
    pid: {p: 50.0, i: 1.0, d: 1.0}

  neck_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_tilt_joint
    pid: {p: 50.0, i: 1.0, d: 1.0}

  eyes_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: eyes_tilt_joint
    pid: {p: 50.0, i: 10.0, d: 1.0}

  version_position_controller:
    type: effort_controllers/JointPositionController
    joint: version_joint
    pid: {p: 1.0, i: 0.1, d: 0.1}

  vergence_position_controller:
    type: effort_controllers/JointPositionController
    joint: vergence_joint
    pid: {p: 1.0, i: 0.1, d: 0.1}

  # Left arm Position Controllers
  l_shoulder_scapula_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_scapula_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_shoulder_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_flection_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_shoulder_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_rotation_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_elbow_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_flection_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_forearm_pronation_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_forearm_pronation_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_wrist_abduction_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_wrist_abduction_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_wrist_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_wrist_flection_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  # Right arm Position Controllers
  r_shoulder_scapula_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_scapula_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_shoulder_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_flection_joint
    pid: {p: 1.0, i: 0.01, d: 0.1}

  r_shoulder_rotation_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_rotation_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_elbow_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_elbow_flection_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_forearm_pronation_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_forearm_pronation_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_wrist_abduction_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_wrist_abduction_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_wrist_flection_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_wrist_flection_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}

  gaze_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
    - r_eye_pan_joint
    - l_eye_pan_joint

