controller_list:
 - name: /vizzy/head_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - neck_pan_joint
      - neck_tilt_joint
      - eyes_tilt_joint
