<?xml version="1.0"?>
<robot  name="vizzy" xmlns:xacro="http://ros.org/wiki/xacro" >
  

  
  <!-- The following included files set up definitions of parts of the robot body -->
  <!-- misc common stuff -->
  <xacro:include filename="$(find vizzy-description)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find vizzy-description)/urdf/mounts/hokuyo_mount.urdf.xacro" />
  <!-- Vizzy base -->
  <xacro:include filename="$(find vizzy-description)/urdf/base/base.urdf.xacro" />
  <!-- Vizzy torso -->
  <xacro:include filename="$(find vizzy-description)/urdf/torso/torso.urdf.xacro" />
  <!-- Vizzy head -->
  <xacro:include filename="$(find vizzy-description)/urdf/head/head.urdf.xacro" />
  <!-- Vizzy left arm -->
  <xacro:include filename="$(find vizzy-description)/urdf/arm/left_arm.urdf.xacro" />
  <!-- Vizzy right arm -->
  <xacro:include filename="$(find vizzy-description)/urdf/arm/right_arm.urdf.xacro" />

  <xacro:base name="base"/>
  <xacro:torso name="torso"/>
  <xacro:head name="head"/>
  <xacro:leftarm name="left_arm" parent="M0" sufix="L" reflect="1">
    <origin xyz="-0.01707 0.0 0.38145"
            rpy="0.0 0.0 0.0" />
  </xacro:leftarm>

  <xacro:rightarm name="right_arm" parent="M0" sufix="R" reflect="1">
    <origin xyz="-0.01707 0.0 0.38145"
            rpy="0.0 0.0 0.0" />
  </xacro:rightarm>

  <!-- Add the hokuyo -->
  <xacro:hokuyo_mount name="nav_hokuyo" parent="base" length="${SENSOR_BEAM_LENGTH*INCH_TO_M}" ros_topic="scan" update_rate="10" min_angle="${-(5 * M_PI)/12}" max_angle="${(5 * M_PI)/12}">
    <origin xyz="-0.05 0.14
 0.15" rpy="${-M_PI/2} ${-M_PI/2} 3.14" />
  </xacro:hokuyo_mount>

  <!-- <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/vizzy</robotNamespace>
    </plugin>
  </gazebo> -->

  <!-- right camera -->
  <gazebo reference="r_camera_link">
    <sensor type="camera" name="r_camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.4912</horizontal_fov>
        <image>
          <width>320</width>
          <height>240</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>vizzy/r_camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>r_camera_link</frameName>
        <distortion>
            <k1>-0.4738</k1>
            <k2>0.190309</k2>
            <k3>0.0</k3>
            <p1>-0.000375676</p1>
            <p2>-0.000663688</p2>
            <center> 0.4809  0.4887</center>
          </distortion>
      </plugin>
    </sensor>
  </gazebo>

  <!-- left camera -->
  <gazebo reference="l_camera_link">
    <sensor type="camera" name="l_camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.4912</horizontal_fov>
        <image>
          <width>320</width>
          <height>240</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>vizzy/l_camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>l_camera_link</frameName>
        <distortion>
            <k1>-0.4738</k1>
            <k2>0.190309</k2>
            <k3>0.0</k3>
            <p1>-0.000375676</p1>
            <p2>-0.000663688</p2>
            <center> 0.4809  0.4887</center>
          </distortion>
      </plugin>
    </sensor>
  </gazebo>
  
</robot>
