docking_frame_id: 'map'
docking_pos_x: 0.24132583584514933
docking_pos_y: -0.07655841494717408
docking_pos_z: 0.0
docking_orient_x: 0.0
docking_orient_y: 0.0
docking_orient_z: 1.0
docking_orient_w: 0.0
